from IlluminaBeadArrayFiles import GenotypeCalls, BeadPoolManifest, code2genotype
from pathlib import Path
import pandas as pd
from argparse import ArgumentParser

args = ArgumentParser()

args.description = """Usage: Uses the `IlluminaBeadArrayFiles` python package to parse the .gtc file along with .bpm (manifest) file to extract relevant data, load in a dataframe and export as TSV."""
args.add_argument(
    "--gtc", nargs=1, help="The .gtc (genotypes) file generated by iaap", required=True
)
args.add_argument(
    "--manifest",
    nargs=1,
    help="The .bpm (manifest) provided by illumina for given array data",
    required=True,
)
args.add_argument(
    "-o", "--output", nargs=1, help="Output file base name", required=True
)

args = args.parse_args()

gtc_file = Path(args.gtc[0])
manifest_file = Path(args.manifest[0])
output = Path(args.output[0])

manifest = BeadPoolManifest(manifest_file)
names = manifest.names
gtc = GenotypeCalls(gtc_file)
genotypes = gtc.get_genotypes()

normalized_intensities = gtc.get_normalized_intensities(manifest.normalization_lookups)


export_df = pd.DataFrame(
    columns=["locus", "snps", "chrom", "pos", "genotypes", "LRR", "BAF"]
)

export_df["locus"] = manifest.names
export_df["snps"] = manifest.snps
export_df["chrom"] = manifest.chroms
export_df["pos"] = manifest.map_infos
export_df["genotypes"] = genotypes
export_df["LRR"] = gtc.get_logr_ratios()
export_df["BAF"] = gtc.get_ballele_freqs()

export_df.to_csv(f"{output}.tsv", sep="\t", index=False)
